mybatis-plus:
    mapper-locations: classpath:/mapper/**.xml
server:
    port: 8080
spring:
    application:
        name: labdemo
    redis:
        host: 127.0.0.1     ## redis所在的服务器IP
        port: 6379

        ## 设置最大连接数，0为无限
        jedis:
            pool:
                max-active: 8
                min-idle: 0
                max-idle: 8
                max-wait: -1
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        username: test
        password: test
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        servlet:
            content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
